version: 2.1

jobs:

  build-ubuntu-bionic:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all python3-all python3-stdeb python3-pyqt5 python3-feedparser gnupg2
            gem install --no-ri --no-rdoc rake
            gem install --no-ri --no-rdoc package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/autocanary_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/ubuntu/bionic deb_dist/autocanary_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/ubuntu/bionic deb_dist/autocanary_${VERSION}-1.dsc

  build-ubuntu-disco:
    docker:
      - image: ubuntu:19.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all python3-all python3-stdeb python3-pyqt5 python3-feedparser gnupg2
            gem install --no-ri --no-rdoc rake
            gem install --no-ri --no-rdoc package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/autocanary_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/ubuntu/disco deb_dist/autocanary_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/ubuntu/disco deb_dist/autocanary_${VERSION}-1.dsc

  build-ubuntu-eoan:
    docker:
      - image: ubuntu:19.10
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all python3-all python3-stdeb python3-pyqt5 python3-feedparser gnupg2
            gem install --no-ri --no-rdoc rake
            gem install --no-ri --no-rdoc package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/autocanary_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/ubuntu/eoan deb_dist/autocanary_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/ubuntu/eoan deb_dist/autocanary_${VERSION}-1.dsc

  build-debian-buster:
    docker:
      - image: debian:buster
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all python3-all python3-stdeb python3-pyqt5 python3-feedparser gnupg2
            gem install --no-ri --no-rdoc rake
            gem install --no-ri --no-rdoc package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/autocanary_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/debian/buster deb_dist/autocanary_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/debian/buster deb_dist/autocanary_${VERSION}-1.dsc

  build-debian-bullseye:
    docker:
      - image: debian:bullseye
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all python3-all python3-stdeb python3-pyqt5 python3-feedparser gnupg2 dh-python
            gem install --no-ri --no-rdoc rake
            gem install --no-ri --no-rdoc package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/autocanary_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/debian/bullseye deb_dist/autocanary_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/debian/bullseye deb_dist/autocanary_${VERSION}-1.dsc

  build-fedora-30:
    docker:
      - image: fedora:30
    steps:
      - run:
          name: Install dependencies
          command: |
            dnf install -y git openssh ruby-devel make automake gcc gcc-c++ rpm-build qt5-devel python3-qt5 python3-feedparser gnupg2
            gem install package_cloud
      - checkout
      - run:
          name: Create the .rpm package
          command: |
            ./install/build_rpm.sh
            dnf install -y dist/autocanary-*-1.noarch.rpm
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/fedora/30 dist/autocanary-${VERSION}-1.noarch.rpm
            package_cloud push firstlookmedia/code/fedora/30 dist/autocanary-${VERSION}-1.src.rpm

  build-fedora-31:
    docker:
      - image: fedora:31
    steps:
      - run:
          name: Install dependencies
          command: |
            dnf install -y git openssh ruby-devel make automake gcc gcc-c++ rpm-build qt5-devel python3-qt5 python3-feedparser gnupg2
            gem install package_cloud
      - checkout
      - run:
          name: Create the .rpm package
          command: |
            ./install/build_rpm.sh
            dnf install -y dist/autocanary-*-1.noarch.rpm
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/fedora/31 dist/autocanary-${VERSION}-1.noarch.rpm
            package_cloud push firstlookmedia/code/fedora/31 dist/autocanary-${VERSION}-1.src.rpm

workflows:
  version: 2
  build-tags:
    jobs:
      - build-ubuntu-bionic:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-ubuntu-disco:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-ubuntu-eoan:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-debian-buster:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-debian-bullseye:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-fedora-30:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-fedora-31:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
